spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/osahaneat
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  privateKey: 2YPzNKPgM13ZXQvXBDg+JtPg5wY/u8wOk/VwffnTnpY=


fileUpload:
  rootPath: D:\__Hoc_Lap_Trinh\Tu hoc\Tu Hoc Java\Cyberlearn\osahaneat\uploads

#logging:
#  level:
#    root: trace
#  file:
#    name: C:\dev.log